#!/bin/bash
. "/usr/bin/variables"

check_rclone_cloud () {
	if [[ ! "$(printenv RCLONE_CLOUD_ENDPOINT)" = *: ]]; then
		printf "\n\n"
		echo "Missing colon (:) in RCLONE_CLOUD_ENDPOINT ($(printenv RCLONE_CLOUD_ENDPOINT))"
		echo "Run: docker exec -ti <DOCKER_CONTAINER> rclone_setup"
		printf "\n\n"

		exit 02
	fi

	if [ "$(rclone listremotes $rclone_config | grep $(printenv RCLONE_CLOUD_ENDPOINT) | wc -l)" == "0" ]; then
		printf "\n\n"
		echo "RCLONE_CLOUD_ENDPOINT ($(printenv RCLONE_CLOUD_ENDPOINT)) endpoint has not been created within rclone"
		echo "Run: docker exec -ti <DOCKER_CONTAINER> rclone_setup"
		printf "\n\n"

		exit 02
	fi
}
